name: soloknows
channels:
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.10.12
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - 'pytorch-cuda=11.7'
  - flask=2.0.2
  - flask-cors
  - 'regex!=2019.12.17'
  - scipy
  - pip
  - pip:
    - transformers
    - 'safetensors>=0.3.1'
    - 'tokenizers!=0.11.3,<0.14,>=0.11.1'
    - git+https://github.com/suno-ai/bark.git
    - psutil
    - python-multipart
    - 'rich>=11.2.0'
    - 'starlette<0.29,>=0.13.5'
    - uvicorn
    - 'httpx<0.25.0,>=0.15.4'
    - 'pydantic<2.0.0,>=1.6.1'
    - tornado>=5.0.2
    - fastapi
    - toml
    - sounddevice
    - requests
    - elevenlabs


